server:
  # ${server.port}
  port: 8080
  servlet:
    # ${server.servlet.context-path}
    context-path: /identity
  cors:
    # ${server.cors.allow-origin}
    allow-origin: ${CORS_ALLOW_ORIGIN}
    # ${server.cors.allow-header}
    allow-header: "*"
    # ${server.cors.allow-method}
    allow-method: "*"

spring:
  application:
    # ${spring.application.name}
    name: "identity-service"
    init-user:
      # ${spring.application.init-user.username}
      username: ${APP_INIT_USERNAME}
      # ${spring.application.init-user.password}
      password: ${APP_INIT_PASSWORD}
  datasource:
    # ${spring.datasource.url}
    url: ${MYSQL_CONNECTION}
    # ${spring.datasource.username}
    username: ${MYSQL_USERNAME}
    # ${spring.datasource.password}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      # ${spring.jpa.hibernate.ddl-auto}
      ddl-auto: update
    # ${spring.jpa.show-sql}
    show-sql: false

jwt:
  # ${jwt.signer-key}
  signer-key: ${JWT_SIGNER_KEY}
  # ${jwt.issuer}
  issuer: ${JWT_ISSUER}
  valid-duration: 3600
  refreshable-duration: 360000
