server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: "identity-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "4hdI75XdHDIFA2TKTvXYW45eOB7N7xV5XtOJEeAxvFlZi3hVm43mav2QHQROSqVE"
  issuer: "localhost.com"
  claim:
    name: "customClaim"
    value: "Custom"